name: Arc themes tag all versions of another arc themes release tag this arc themes release new tag 
on: 
  workflow_dispatch:
    inputs:
      target_release_tag:
        description: 'Base tag (eg, 1.18 if 1.18 -> 1.19)'
        required: true
      new_release_tag:
        description: 'New tag (eg, 1.19 if 1.18 -> 1.19)'
        required: true

jobs:
  retag:
    name: Tag all versions of another tag this new tag
    runs-on: ubuntu-latest
    env: 
      TARGET_RELEASE_TAG: arc-themes-release-${{ github.event.inputs.target_release_tag }}
      NEW_RELEASE_TAG: arc-themes-release-${{ github.event.inputs.new_release_tag }}
    # ensure new and target release tags match regex: 
    # {number}.{number} per product
    # +: Matches one or more of the preceding character.
    # [0-9]: Matches digits
    if: contains(github.event.inputs.target_release_tag, '[0-9]+.[0-9]+') && contains(github.event.inputs.new_release_tag, '[0-9]+.[0-9]+')

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node and NPM
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://npm.pkg.github.com'
          
      - name: Get version of target tag and point the new tag to that version
        run: npx lerna exec --stream --no-bail --concurrency 1 -- 'PKG_VERSION=$(npm v . dist-tags.${{ env.TARGET_RELEASE_TAG }}); [ -n "$PKG_VERSION" ] && (npm dist-tag add ${LERNA_PACKAGE_NAME}@${PKG_VERSION} ${{ env.NEW_RELEASE_TAG }}) || exit 0'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}