name: Arc themes tag all versions of another arc themes release tag this arc themes release new tag 
on: 
  workflow_dispatch:
    inputs:
      target_release_tag:
        description: 'Base tag (eg, 1.18 if 1.18 -> 1.19)'
        required: true
      new_release_tag:
        description: 'New tag (eg, 1.19 if 1.18 -> 1.19)'
        required: true

jobs:
  validate_tags:
    name: Validate release numbers
    runs-on: ubuntu-latest

    steps:
      - name: Check target release tag name
        id: check-target-tag
        run: |
          if [[ ${{ github.event.inputs.target_release_tag }} =~ ^([0-9]+)\.([0-9]+)\.?$ ]]; then
              echo ::set-output name=match::true
          fi
      
      - name: Check new release tag name
        id: check-new-tag
        run: |
          if [[ ${{ github.event.inputs.new_release_tag }} =~ ^([0-9]+)\.([0-9]+)\.?$ ]]; then
              echo ::set-output name=match::true
          fi
      
      # ensure new and target release tags match regex: 
      # {number}.{number} per product
      # +: Matches one or more of the preceding character.
      # [0-9]: Matches digits
      - name: Validate release tag numbers
        id: validate-release-tag-numbers
        if: steps.check-target-tag.outputs.match == 'true' && steps.check-new-tag.outputs.match == 'true'
        run: |
          echo "Tags match correct syntax (eg, 1.18)"

  retag:
    name: Tag all versions of another tag this new tag
    runs-on: ubuntu-latest
    needs: validate_tags
    env: 
      TARGET_RELEASE_TAG: arc-themes-release-${{ github.event.inputs.target_release_tag }}
      NEW_RELEASE_TAG: arc-themes-release-${{ github.event.inputs.new_release_tag }}
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node and NPM
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://npm.pkg.github.com'
          
      - name: Get version of target tag and point the new tag to that version
        run: npx lerna exec --stream --no-bail --concurrency 1 -- 'PKG_VERSION=$(npm view ${LERNA_PACKAGE_NAME}@${{ env.TARGET_RELEASE_TAG }} version); [ -n "$PKG_VERSION" ] && (npm dist-tag add ${LERNA_PACKAGE_NAME}@${PKG_VERSION} ${{ env.NEW_RELEASE_TAG }}) || exit 0'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}