name: Format test
on:
  push:
    branches:
      - CI-format-branch-name-1.19


jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    env:
      SYNCED_RELEASE_TAG: ${{ github.ref_name }} # targets branch name ref_name

    steps:
      - name: Example find and replace
        id: example
        run: |
          ref="${SYNCED_RELEASE_TAG//./-}"

          echo $ref

          echo "::set-output name=ref::$ref"
        
      - run: |
          echo "${{ steps.example.outputs.ref }}"

      - name: Get branch without dots
        id: format-version
        # message='The secret code is 12345'
        # echo "${message//[0-9]/X}"           
        # prints 'The secret code is XXXXX'
        # "s/[original]/[target]/g"
        run: echo "::set-output name=version::$(echo "${${{ env.SYNCED_RELEASE_TAG }}//./-}")"

      - name: Show get version
        id: show-version
        run: echo ${{ steps.format-version.outputs.version }} "${{ steps.format-version.outputs.version }}"