name: Publish to stable
on:
  push:
    branches:
      - stable

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
    steps:
      - name: Set git username
        run: git config --global user.email "jackhowa@hey.com" && git config --global user.name "jackhowa"

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.NODE_AUTH_TOKEN }}
        
      # pulls all tags (needed for lerna / semantic release to correctly version)
      # - name: Pull tags to give lerna access to git info
      #   run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Configure NPM
        run: |
          echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" > .npmrc
          echo '@JackHowa:registry=https://npm.pkg.github.com' >> .npmrc

      - name: Install
        run: npm ci
      
      - name: Publish to stable
        run: npm run release:stable
