name: Release All By Your Name
on: 
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Define release tag. Cannot be: canary, rc, hotfix, beta, stable, latest'     
        required: true

jobs:
  publish:
    name: All block publish
    if: github.events.inputs.release_tag != 'canary' && github.events.inputs.release_tag != 'rc' && github.events.inputs.release_tag != 'hotfix' && github.events.inputs.release_tag != 'beta' && github.events.inputs.release_tag != 'stable' && github.events.inputs.release_tag != 'latest'
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      RELEASE_TAG: ${{ github.events.inputs.release_tag }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12"
          registry-url: "https://npm.pkg.github.com"

      - name: Clean install (CI) dependencies if lockfile (above) changed
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      - name: Run all tests
        run: npm run test

      - name: Show variables set
        run: |
          echo "Target tag: ${{ github.events.inputs.release_tag }}"
          echo "All inputs ${{ github.events.inputs }}"
          echo "All env ${{ env }}"
  
      - name: Get current datetime for re-running publish if necessary
        id: get-datetime
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      # - name: Publish all to tag name specified
      #   run: npx lerna publish 0.0.0-${{ env.RELEASE_TAG }}.$(git rev-parse --short HEAD).${{ steps.get-datetime.outputs.date }} --no-git-tag-version --no-push --dist-tag ${{ env.RELEASE_TAG }} --yes
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
