name: Update one package of the monorepo
on: [workflow_dispatch]

jobs:
  tag:
    uses: wpmedia/github-actions-helpers/.github/workflows/tag-another-tags-version.yml@main
    with:
      base_tag: canary
      new_tag: stable
      package_name: "@wpmedia/description"

